version: '3'
services:
  back:
    build: ./
    # volumes:
    #   - ./node_modules:/node_modules
    #   - ./package.json:/package.json
    #   - ./tsconfig.json:/tsconfig.json
    ports:
      - 3000:3000
    command: yarn ts-node ./app/index.ts
  mongo: 
    image: mongo